# Generated by Django 4.1.7 on 2023-06-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbquiz', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='e_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
