# Generated by Django 4.1.7 on 2023-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbquiz', '0003_remove_employee_e_id_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_pic', models.ImageField(default='giftimg.jpg', upload_to='gifts')),
                ('gname', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('points_needed', models.FloatField()),
                ('rank_needed', models.IntegerField()),
                ('gdate', models.DateTimeField()),
            ],
        ),
    ]
