# Generated by Django 4.1.7 on 2023-07-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbquiz', '0005_alter_gift_gdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gift',
        ),
    ]
