# Generated by Django 4.1.7 on 2023-06-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
