# Generated by Django 4.1.7 on 2023-06-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points',
        ),
    ]
