# Generated by Django 4.1.7 on 2023-06-22 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0003_delete_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='points',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('point', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
