# Generated by Django 4.1.7 on 2023-06-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
