# Generated by Django 4.1.7 on 2023-06-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='institute',
            new_name='ecountry',
        ),
    ]
