# Generated by Django 4.1.7 on 2023-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0009_alter_profile_ecountry_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.ImageField(default='defaultprofile.jpg', upload_to='profile'),
        ),
    ]
