# Generated by Django 4.1.7 on 2023-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0010_alter_customuser_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='write your bio here'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='city', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='country', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ecountry',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='education', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ins_name',
            field=models.CharField(default='institute', max_length=100),
        ),
    ]
