# Generated by Django 4.1.7 on 2023-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0012_alter_points_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points',
        ),
    ]
