# Generated by Django 4.1.7 on 2023-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0014_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
