# Generated by Django 4.1.7 on 2023-07-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0016_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points',
        ),
    ]
