# Generated by Django 4.1.7 on 2023-07-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0018_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='total_coins',
            new_name='total_rights',
        ),
    ]
