# Generated by Django 4.1.7 on 2023-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0019_rename_total_coins_ranking_total_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=False, max_length=15),
        ),
    ]
