# Generated by Django 4.1.7 on 2023-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0020_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_grabber',
            fields=[
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
