# Generated by Django 4.1.7 on 2023-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0021_otp_grabber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default=False),
        ),
    ]
