# Generated by Django 4.1.7 on 2023-07-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0022_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
