# Generated by Django 4.1.7 on 2023-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0023_profile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
