# Generated by Django 4.1.7 on 2023-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0026_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AddField(
            model_name='query',
            name='cemail',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='cfname',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='clname',
            field=models.TextField(blank=True, default=False),
        ),
    ]
