# Generated by Django 4.1.7 on 2023-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0027_remove_query_user_query_cemail_query_cfname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
