# Generated by Django 4.1.7 on 2023-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0028_query_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
