# Generated by Django 4.1.7 on 2023-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0030_alter_query_ctime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='query',
        ),
    ]
