# Generated by Django 4.1.7 on 2023-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0031_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemail', models.TextField(blank=True, default=False)),
                ('cfname', models.TextField(blank=True, default=False)),
                ('clname', models.TextField(blank=True, default=False)),
                ('problem', models.TextField(blank=True, default=False)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
