# Generated by Django 4.1.7 on 2023-07-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0032_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='query',
        ),
    ]
