# Generated by Django 4.1.7 on 2023-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0034_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='total_que',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
