# Generated by Django 4.1.7 on 2023-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0035_points_total_que'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='replied_by',
            field=models.TextField(blank=True, default='-1'),
        ),
    ]
