# Generated by Django 4.1.7 on 2023-07-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0038_alter_query_replied_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='replied',
            fields=[
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bbhome.query')),
                ('replied_by', models.EmailField(blank=True, default='-1', max_length=100)),
                ('rtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='replied_by',
        ),
        migrations.AlterField(
            model_name='query',
            name='problem',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
    ]
