# Generated by Django 4.1.7 on 2023-07-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0039_replied_remove_query_replied_by_alter_query_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
