# Generated by Django 4.1.7 on 2023-08-17 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbhome', '0041_query_replied_by_delete_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('gift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cprice', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
